apiVersion: v1
kind: Service
metadata:
  name: alertmanager-server
  namespace: monitoring
  labels:
    app: alertmanager-server
  # annotations:
  #   prometheus.io/scrape: 'true'
spec:
  type: NodePort
  ports:
    - port: 9093
      protocol: TCP
      name: webui
      nodePort: 32052
  selector:
    app: alertmanager-server
